# Generated by Django 5.1.1 on 2025-08-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_achievements_achievementcat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.RenameField(
            model_name='achievementcat',
            old_name='cats',
            new_name='cat',
        ),
    ]
