# Generated by Django 5.1.1 on 2025-08-19 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_rename_achievements_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(through='cats.AchievementCat', to='cats.achievement'),
        ),
        migrations.AlterField(
            model_name='achievementcat',
            name='achievements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.achievement'),
        ),
    ]
