# Generated by Django 5.1.1 on 2025-08-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_cat_achievements_alter_achievementcat_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementcat',
            old_name='achievements',
            new_name='achievement',
        ),
    ]
